/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#b5b8c1',
        'error-container': '#93000a',
        'inverse-surface': '#e1e3e4',
        'primary-fixed-dim': '#8bdc00',
        'on-tertiary-fixed-variant': '#3d4756',
        'on-background': '#e1e3e4',
        surface: '#111415',
        'on-surface': '#e1e3e4',
        'on-secondary-fixed-variant': '#43474e',
        'surface-bright': '#373a3b',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#bdc7d9',
        'surface-tint': '#8bdc00',
        'on-error': '#690005',
        'surface-container-lowest': '#0c0f10',
        'surface-dim': '#111415',
        background: '#111415',
        'surface-container-low': '#191c1d',
        'primary-fixed': '#9ffb00',
        'on-primary': '#1f3700',
        'surface-container-highest': '#323536',
        'secondary-fixed': '#dfe2eb',
        'on-surface-variant': '#c0caad',
        'on-primary-container': '#457000',
        'on-tertiary': '#27313f',
        'secondary-fixed-dim': '#c3c6cf',
        'on-primary-fixed': '#102000',
        secondary: '#c3c6cf',
        primary: '#ffffff',
        'surface-variant': '#323536',
        'on-secondary-fixed': '#181c22',
        'inverse-primary': '#406900',
        'on-secondary': '#2d3137',
        'on-error-container': '#ffdad6',
        'surface-container': '#1d2021',
        'outline-variant': '#414a34',
        'inverse-on-surface': '#2e3132',
        outline: '#8a947a',
        'secondary-container': '#454950',
        'on-tertiary-container': '#5b6575',
        'surface-container-high': '#282a2b',
        'on-primary-fixed-variant': '#2f4f00',
        'tertiary-container': '#d9e3f6',
        'primary-container': '#9ffb00',
        'on-tertiary-fixed': '#121c2a',
        'tertiary-fixed': '#d9e3f6',
        tertiary: '#ffffff',
        'neon-green': '#a2ff00',
        'emergency-red': '#ff3b3b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        unit: '4px',
        'margin-mobile': '16px',
        'container-max': '1800px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'data-label': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'headline-md': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'data-value': ['JetBrains Mono'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'data-label': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-value': ['20px', { lineHeight: '1.0', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
